print ("energy-monitor v0.1a by luisau")
print ("USAGE:")
print ("  energy-monitor-text     (will run a text based version)")
print ("  energy-monitor-graphic  (will run a graphic version)")
print ("REQUIREMENTS:")
print ("  - Place an Adapter Block in contact with one of your Energy Pylons")
print ("  - Connect the Adapter Block through cables to the computer")
print ("  - Only tested with tier 3 computers.")
print ("BUG REPORTS: Find me on Discord:  luisau#0826")
print ()